transformation:
  title: Skulpturale Schwebungen
  title_en: Sculptural Beatings
  audio_index: 11
  video_index: 11
  duration:
    minutes: 15
    seconds: 12
  description: >
    Skulpturale Schwebungen schweben Skulptural
