block_b:
  length: 170
  track_padding: 10
  tracks:
    - trailer
    - transformation
    - thepassage
    - pune
    - brunnen
    - sufi
    - iwillnotweep
    - trailer
    - oksus
    - liquidcontinent
    - doublefeedback
