block_a:
  length: 170
  track_padding: 10
  tracks:
    - trailer
    - pune
    - brunnen
    - sufi
    - datenerhebung
    - iwillnotweep
    - trailer
    - oksus
    - liquidcontinent
    - thepassage
    - doublefeedback
